/**
 * REAL predicted-vs-actual RUL for the deployed LSTM+Attention model.
 * Generated by running the 100 held-out FD001 test engines
 * (data/raw/test_FD001.txt) through the live `/predict` endpoint; actual
 * RUL is the FD001 ground truth (RUL_FD001.txt), capped at 125 to match the
 * piecewise training target. Bundled statically so the Model Performance
 * page shows measured results with no live dependency.
 *
 * Recomputed on these points: RMSE 14.44, MAE 10.22, NASA 540.5, within ±10 60.0%, within ±25 92.0%.
 */
export interface PredActual {
  actual: number;
  predicted: number;
}

export const REAL_PRED_VS_ACTUAL: PredActual[] = [
  { actual: 112.0, predicted: 113.7 },
  { actual: 98.0, predicted: 127.6 },
  { actual: 69.0, predicted: 51.7 },
  { actual: 82.0, predicted: 85.1 },
  { actual: 91.0, predicted: 106.2 },
  { actual: 93.0, predicted: 115.0 },
  { actual: 91.0, predicted: 104.3 },
  { actual: 95.0, predicted: 90.0 },
  { actual: 111.0, predicted: 123.2 },
  { actual: 96.0, predicted: 94.0 },
  { actual: 97.0, predicted: 95.0 },
  { actual: 124.0, predicted: 112.1 },
  { actual: 95.0, predicted: 86.5 },
  { actual: 107.0, predicted: 118.7 },
  { actual: 83.0, predicted: 106.7 },
  { actual: 84.0, predicted: 97.6 },
  { actual: 50.0, predicted: 51.3 },
  { actual: 28.0, predicted: 25.3 },
  { actual: 87.0, predicted: 104.3 },
  { actual: 16.0, predicted: 17.4 },
  { actual: 57.0, predicted: 73.8 },
  { actual: 111.0, predicted: 125.6 },
  { actual: 113.0, predicted: 120.1 },
  { actual: 20.0, predicted: 19.4 },
  { actual: 125.0, predicted: 114.0 },
  { actual: 119.0, predicted: 109.8 },
  { actual: 66.0, predicted: 85.8 },
  { actual: 97.0, predicted: 108.6 },
  { actual: 90.0, predicted: 100.3 },
  { actual: 115.0, predicted: 114.2 },
  { actual: 8.0, predicted: 7.8 },
  { actual: 48.0, predicted: 50.1 },
  { actual: 106.0, predicted: 120.3 },
  { actual: 7.0, predicted: 2.3 },
  { actual: 11.0, predicted: 10.0 },
  { actual: 19.0, predicted: 22.2 },
  { actual: 21.0, predicted: 19.4 },
  { actual: 50.0, predicted: 54.2 },
  { actual: 125.0, predicted: 122.1 },
  { actual: 28.0, predicted: 30.4 },
  { actual: 18.0, predicted: 12.4 },
  { actual: 10.0, predicted: 2.6 },
  { actual: 59.0, predicted: 64.8 },
  { actual: 109.0, predicted: 115.3 },
  { actual: 114.0, predicted: 86.1 },
  { actual: 47.0, predicted: 45.3 },
  { actual: 125.0, predicted: 119.5 },
  { actual: 92.0, predicted: 114.6 },
  { actual: 21.0, predicted: 17.4 },
  { actual: 79.0, predicted: 112.7 },
  { actual: 114.0, predicted: 112.4 },
  { actual: 29.0, predicted: 30.2 },
  { actual: 26.0, predicted: 27.0 },
  { actual: 97.0, predicted: 120.5 },
  { actual: 125.0, predicted: 117.1 },
  { actual: 15.0, predicted: 16.0 },
  { actual: 103.0, predicted: 117.3 },
  { actual: 37.0, predicted: 46.1 },
  { actual: 114.0, predicted: 109.7 },
  { actual: 100.0, predicted: 114.9 },
  { actual: 21.0, predicted: 18.6 },
  { actual: 54.0, predicted: 39.7 },
  { actual: 72.0, predicted: 89.5 },
  { actual: 28.0, predicted: 23.3 },
  { actual: 125.0, predicted: 121.6 },
  { actual: 14.0, predicted: 19.7 },
  { actual: 77.0, predicted: 122.3 },
  { actual: 8.0, predicted: 6.7 },
  { actual: 121.0, predicted: 122.6 },
  { actual: 94.0, predicted: 84.1 },
  { actual: 118.0, predicted: 114.1 },
  { actual: 50.0, predicted: 59.6 },
  { actual: 125.0, predicted: 103.9 },
  { actual: 125.0, predicted: 106.1 },
  { actual: 113.0, predicted: 110.7 },
  { actual: 10.0, predicted: 7.3 },
  { actual: 34.0, predicted: 29.4 },
  { actual: 107.0, predicted: 124.8 },
  { actual: 63.0, predicted: 115.3 },
  { actual: 90.0, predicted: 111.2 },
  { actual: 8.0, predicted: 6.8 },
  { actual: 9.0, predicted: 7.2 },
  { actual: 125.0, predicted: 127.9 },
  { actual: 58.0, predicted: 86.8 },
  { actual: 118.0, predicted: 128.9 },
  { actual: 89.0, predicted: 119.9 },
  { actual: 116.0, predicted: 116.1 },
  { actual: 115.0, predicted: 122.5 },
  { actual: 125.0, predicted: 119.2 },
  { actual: 28.0, predicted: 27.2 },
  { actual: 38.0, predicted: 25.8 },
  { actual: 20.0, predicted: 22.3 },
  { actual: 85.0, predicted: 45.6 },
  { actual: 55.0, predicted: 71.1 },
  { actual: 125.0, predicted: 111.6 },
  { actual: 125.0, predicted: 107.9 },
  { actual: 82.0, predicted: 84.9 },
  { actual: 59.0, predicted: 68.8 },
  { actual: 117.0, predicted: 119.3 },
  { actual: 20.0, predicted: 17.3 },
];

const within = (band: number) =>
  Math.round(
    (100 * REAL_PRED_VS_ACTUAL.filter((p) => Math.abs(p.actual - p.predicted) <= band).length) /
      REAL_PRED_VS_ACTUAL.length,
  );

/** Accuracy bands recomputed from the bundled points, so captions match the scatter. */
export const REAL_EVAL = {
  count: REAL_PRED_VS_ACTUAL.length,
  within10: within(10),
  within25: within(25),
};

